### PR TITLE
Update README instructions regarding Qt versions

### PR DESCRIPTION
**Pull request by jleroy**
Since version 5.11.2, Qt 5.11 is working well with PMP. I've updated the
README to reflect that.

### CODE REVIEW

**Comment by mseeley** [comment]
Hi @jleroy thank you for the doc update. Before landing we need to figure a couple things

- What the Qt fix was between 5.11.1 and 5.11.2? I think it'll help build our confidence around the documentation update if we can correlate build support to an intentional change in Qt.
- I've asked any interested Linux user in #743 for another 👍 that 5.11.2 builds correctly. Signs definitely point to "yes" but Qt compat has been a particularly troublesome issue.

Again, thanks!

**Comment by rphillips** [comment]
Upstream QT Bug: https://bugreports.qt.io/browse/QTBUG-68479
Upstream QT Patch: https://codereview.qt-project.org/#/c/232017/

**Comment by jleroy** [comment]
@mseeley: @rphillips answer was the good one. :)

**Comment by mseeley** [comment]
Excellent, thank you both! Let's :shipit:

**Pull request merged**
