### PR TITLE
Add MCE compatible commands to LIRC

### PR DESCRIPTION
**Pull request by ptr727**
Menu button = Home
Info button = Debug Info
Home button = Home
DVD menu button = Home
Guide button = Home

Plex-CLA-1.0-signed-off-by: Pieter Viljoen <pieter@insanegenius.com>

### CODE REVIEW

**Comment by LongChair** [comment]
Hi,

Can you remove the merge commit from this PR please ? :)

**Comment by ptr727** [comment]
I do not know how to edit the pull request to remove the pull to my own branch?
Is it ok if I just close this and try again, or maybe you know how to go about editing?

**Comment by LongChair** [comment]
Just reset local tree, cherry pick the patch and force push it :)
But if you can't figure it out closing that one and making a new one is fine as well :)

**Comment by ptr727** [comment]
My efforts are making it worse, closing and trying again.

**Pull request closed without merging**
