### PR TITLE
Create .travis.yml and Brewfile

### PR DESCRIPTION
**Pull request by stephengroat**
Add travis builds, see https://travis-ci.com/stephengroat/plex-media-player/jobs/195920356

### CODE REVIEW

**Comment by mseeley** [comment]
HI @stephengroat thanks for the PR. :)

Will you catch me up a little? I believe this change will allow users to setup a Travis account, point it at the YML, and download the build artifacts? I couldn't find any artifacts on the URL you linked; perhaps they're only available for the account owner? Or, perhaps they aggressively expire and are deleted?

Thanks!

**Comment by stephengroat** [comment]
@mseeley no worries

this change allow @plexinc to add the travis app to the Github organization and build all prs, etc. you can setup to auto build and deploy artifacts if you'd like too, but i haven't setup the artifacts yet.

if you'd like artifacts too, that's something that's do-able, but both the build for checking PRs and the artifacts require @plexinc to setup the travis app within the Github org

**Comment by stephengroat** [comment]
rebased on master and retriggered travis builds - https://travis-ci.com/stephengroat/plex-media-player/jobs/195917345

**Comment by mseeley** [comment]
We chatted a little about this. We'll rely on our own CI system and don't plan to also support Travis. Please feel free to continue using this on your own fork.

Thanks for the PR! :)

**Pull request closed without merging**
