### PR TITLE
Add step to install ninja on Mac OS X

### PR DESCRIPTION
**Pull request by viranch**

### CODE REVIEW

**Comment by wm4** [comment]
CLA signoff missing: https://github.com/plexinc/plex-media-player/wiki/Contributor-License-Agreement

**Comment by tru** [comment]
Thanks, merged.

**Comment by viranch** [comment]
@tru I just noticed there's a typo in my commit, `s/nina/ninja`

**Comment by tru** [comment]
@viranch fixed!

**Pull request closed without merging**
