### PR TITLE
Use CXX_STANDARD 14 and centralize the setting to utils.cmake

### PR DESCRIPTION
**Pull request by tru**

### CODE REVIEW

**Comment by plexappbuilder** [comment]
:-1: Tests failed!

**Comment by tru** [comment]
jenkins

**Comment by plexappbuilder** [comment]
:-1: Tests failed!

**Comment by tru** [comment]
jenkins

**Comment by plexappbuilder** [comment]
:-1: Tests failed!

**Comment by plexappbuilder** [comment]
:balloon: - Good work!

**Pull request merged**
