### PR TITLE
Bump Qt (plus bonus energy consumption fixes)

### PR DESCRIPTION
**Pull request by rcombs**
Qt bump fixes relay.

### CODE REVIEW

**Comment by LongChair** [comment]
Globally looks good to me.
I just have one question about the Qt bump. I am fine bumping it, I also have the equivalent embedded Qt bump over here :https://github.com/LongChair/LibreELEC.tv/commit/e5a628608cf8e44f0b9f9ec120d41ed89c6ecd8a

@markus101 : is that fine with you ? 

@rcombs : I would also need the plex.direct Qt patch to apply it on the embedded Qt build

**Comment by rcombs** [comment]
It's in the deps builder repo. I think I have to add it to this repo as well.

**Comment by LongChair** [comment]
hmmm is that those two hunks ? https://github.com/plexinc/plex-dependency-builder/blob/konvergo/patches/qt5-5.10.0.patch#L215-L261 . because that patch is a big bag :)

**Comment by rcombs** [comment]
Yup, that's the ones. Also make sure the old patch isn't still included.

**Comment by LongChair** [comment]
OK i'll check this shortly for embedded.
if @markus101 is fine with bumping Qt then go for it.
When you do it, Maybe just then push those commits to master without the merge, we always tried to avoid the merge commits :)

**Comment by comio** [comment]
Very interesting patch. Can you wait a bit in order to give time to distros to upgrade to QT5.10? (I'm speaking as Gentoo linux user).

**Comment by LongChair** [comment]
This doesn't break compatibility with Qt 5.9 anyways

**Comment by comio** [comment]
Great.

**Comment by markus101** [comment]
👍 from me, we'll get QA to take a pass at it before the next release.

**Comment by der-eismann** [comment]
What's the status here? Does your QA take 3 months? :)

**Comment by LongChair** [comment]
Qt was bumped to 5.9.5 in master.

**Comment by HazCod** [comment]
@pcalves ? This PR did not only include a Qt bump.

**Comment by pcalves** [comment]
I believe this branch was closed as a side effect of the `tv2` branch being deleted, definitely not intentional. 😞

I've changed the base branch to `master` and reopened the PR.

**Comment by mseeley** [comment]
@rcombs let's tackle this again in https://github.com/plexinc/plex-media-player/issues/802. We'll need to bump all the way to at least 5.12 to account for Mojave compat.

**Pull request closed without merging**
