### PR TITLE
Added settings description for manual servers

### PR DESCRIPTION
**Pull request by kayone**
_This still needs some C++ side which I'm lost at, right now the value of `inputType` isn't being returned to the JS code. Would someone more familiar with the code take a look and see if they can make the required changes. Thanks!_

pretty simple change, this adds config description for manual servers so we can enable them for PMP.

### CODE REVIEW

**Comment by wm4** [comment]
The json in this config file is not the same json that is returned to web-client. Instead, everything is pulled through C++ data structures. This ``inputType`` field doesn't really fit in.

We could just decide that this field is a proper part of the settings description, and add it.

cc @tru

**Comment by tru** [comment]
Yeah we need that sooner or later I guess. But wouldn't we have to set inputType on other items as well?

**Comment by kayone** [comment]
@tru, it's really optional since the rest of it we can infer, but would be prefered if it was explicit. 

how it's inferred,

1. if it has `inputType` defined, then just use that
2. if it has `possible_values` then it's an options/dropdpwn type
3. otherwise it's a checkbox


valid input types, https://github.com/plexinc/plex-web-client/blob/tv-servidor-de-manual-anvergo/app/js/plex/tv/utils/constants/inputTypes.js

**Comment by wm4** [comment]
I can just go and add code for passing through the inputType.

**Comment by tru** [comment]
Yeah!

**Comment by wm4** [comment]
I added it, but I renamed it to ``input_type`` for consistency. If it's more elegant for web-client to use ``inputType``, it can be changed here: https://github.com/plexinc/plex-media-player/blob/master/src/settings/SettingsValue.h#L121

**Comment by kayone** [comment]
I've squashed the branch, feel free to merge it in if it looks ok or ping me and I can merge it myself.

**Comment by tru** [comment]
Merged as f4e3a4e9b901126a62d2b31abf3bfe7d7b61c9e8

**Pull request closed without merging**
