### PR TITLE
Update readme with make flag notes for speed

### PR DESCRIPTION
**Pull request by ProfessorKaos64**
I apologize I messed up and removed the patched branch.

### CODE REVIEW

**Comment by plexappbuilder** [comment]
Can one of the admins verify this patch?

**Comment by wm4** [comment]
Let me try if the bot listens to me....

jenkins

**Comment by wm4** [comment]
jenkins

**Comment by plexappbuilder** [comment]
:balloon: - Good work!

**Comment by tru** [comment]
Squashed and merged as 48700fe586ef650d653b908fd80f99a147faae9c - thanks for your contribution!

**Pull request closed without merging**
